import "../globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  balance,
  expenses,
  profit,
  customers,
}) {
  return (
    <div className="m-4 flex flex-col flex-grow gap-4 items-center">
      {children}
      <div className="flex justify-between gap-4 w-full">
        {balance}
        {expenses}
        {profit}
      </div>
      {customers}
    </div>
  );
}
